# Generated by Django 4.2 on 2026-06-07 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_service_websitesettings_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Service',
            new_name='service',
        ),
    ]
