# Generated by Django 4.2 on 2026-06-15 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_service_service_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='makeup_type',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service_type',
            new_name='service_group',
        ),
    ]
